### ISSUE TITLE
Image uploading

### ISSUE THREAD

**Issue by heyrict** [heyrict/cindy-next-rust#1]
## Description
Images can be a bonus for creating lateral thinking puzzles. Generally users may want to use one or two images in a single puzzle.

## Proposed solution
IMO, a table storing paths to pictures and uploaded users, file size, modification time, etc. should be created (one-to-many relationship between user and images may be sufficient in this case), thus alternation in the database is required.
Database alternation is done by files in the `migrations` folder, created with `diesel migration generate`. See files there as an example.

The graphql endpoint for uploading files is implemented in `async-graphql`, [documented here](https://docs.rs/async-graphql/2.10.0/async_graphql/types/struct.Upload.html).

## Alternative solutions
Adding an optional field in `puzzle` table may allow user to use up to one picture, associated with the puzzle. This could be easier to implement with the cost of flexibility.

**Comment by pb10005** [comment]
I added a column named `content_image` to `puzzle` table.
https://github.com/pb10005/cindy-next-rust/commit/6b0c0c31ec3428960b5b6f784c65bde09a1b3ac8

**Comment by heyrict** [comment]
> I added a column named `content_image` to `puzzle` table.
> [pb10005@6b0c0c3](https://github.com/pb10005/cindy-next-rust/commit/6b0c0c31ec3428960b5b6f784c65bde09a1b3ac8)

Hey @pb10005 ! Thank you for participating! The code is good to start with :) Going to assign the issue to you if you don't mind.

---

Edit: you may want to update the schema code `diesel print-schema > src/schema.rs`
